version: '2.4'

services:
  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    ports:
     - 8888:8888
    networks:
      backend:
        aliases:
          - config-server

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8761:8761
    networks:
      backend:
        aliases:
          - discovery-server

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
    - 8081:8081
    networks:
      backend:
        aliases:
          - customers-service

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8082:8082
    networks:
      backend:
        aliases:
          - visits-service

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8083:8083
    networks:
      backend:
        aliases:
          - vets-service

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8080:8080
    networks:
      backend:
        aliases:
          - api-gateway

networks:
  backend:
    driver: bridge
